DIR=./


GCC=g++
INC=-I ${DIR}/ -I ../CNN/


#bpnn.o:bpnn.cpp
#	g++ -c bpnn.cpp -g ${INC} -o bpnn.o

bpnn.o:bpnn.cpp
	g++ -c bpnn.cpp -g ${INC} -o ../Obj/bpnn.o
	

clean:
	rm -rf ../Obj/bpnn.o
